apiVersion: v1
kind: Service
metadata:
  name: quantum-flow-app-service
spec:
  selector:
    app: quantum-flow-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
