apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-flow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum-flow-postgres
  template:
    metadata:
      labels:
        app: quantum-flow-postgres
    spec:
      containers:
      - name: quantum-flow-postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_db
        ports:
        - containerPort: 5432
